kind: pipeline
name: Buildar e Publicar

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
        from_secret: username
    password:
        from_secret: password
    repo: pepinoselvagem/msf
    tags: latest