version: "2.2"
services:
msfandroid: 
                image: msf:latest
                networks: backdoor
                ports:
                        - 5556:5556'
                command: msfconsole -r /rc/android
    volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - /rc:/rc
