version: "2.2"
services:
  msfandroid: 
   image: msf
   container_name: msfandroid
   stdin_open: true
   tty: true
   networks:
      static-network:
        ipv4_address: 172.20.0.22
   ports:
    - 5556:5556
   command: msfconsole -r /rc/android
   volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - /rc:/rc
msfunix: 
   image: msf
   container_name: msfunix
   stdin_open: true
   tty: true
   networks:
      static-network:
        ipv4_address: 172.20.0.23
   ports:
    - 5557:5557
   command: msfconsole -r /rc/unix
   volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - /rc:/rc
msfwindows: 
   image: msf
   container_name: msfwindows
   stdin_open: true
   tty: true
   networks:
      static-network:
        ipv4_address: 172.20.0.24
   ports:
    - 5555:5555
   command: msfconsole -r /rc/windows
   volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - /rc:/rc
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
