version: "2.2"
services:
  msfandroid: 
   image: msf
   networks:
      static-network:
        ipv4_address: 172.18.0.22
   ports:
    - 5556:5556
   command: msfconsole -r /rc/android
   volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - /rc:/rc
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16