version: 1.0
services:
    build:
        network: backdoor
    msfandroid: 
        image: msf
        ports:
            - 5556:5556'
        command: msfconsole -r /rc/android
    volumes:
        - ~/.msf4:/root/.msf4
        - /tmp/msf:/tmp/data
        - /rc:/rc
    restart: allways