version: "2.2"
services:

  msfmulti: 
   image: pepinoselvagem/msf
   container_name: msfwindows
   stdin_open: true
   tty: true
   networks:
      static-network:
        ipv4_address: 172.20.0.24
   ports:
    - 5555:5555
    - 55552:55552
    - 5556:5556
   command: /usr/local/bin/init.sh && /rc/multi.sh 
   volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - /rc:/rc
    - /rc/db:/var/lib/postgresql/data
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
